#spring:
#  jackson:
#    serialization:
#      fail-on-empty-beans: false     
#  datasource:
#    url: jdbc:mysql://localhost:3306/foodapp
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    
#    hibernate:
#      naming:
#        physical-strategy: com.learning.Utils.CustomNamingStrategy
#      ddl-auto: create
#server:
#  port: 9006
#  servlet:
#    context-path: /api
#    

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3306/foodapp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
    hibernate:
      naming:
        physical-strategy: com.learning.Utils.CustomNamingStrategy
      ddl-auto: update
  
server:
  port: 9005

learning:
  app:
    jwtSecret: seretkey
    jwtExpirationMs: 86400000